### PR TITLE
Merge linux driver

### PR DESCRIPTION
**Pull request by fabiscafe**
This is a huge change to the way we deal with the free drivers.

Linux and Xorg are capable of dealing with opensource drivers themself. They can load and unload modules, deal with hybrid graphics, check for OpenGL and Vulkan support and know the hardware that is supported.

mhwd on the other hand is blocking this. mhwd needs us as users to constantly check for PCIID updates, because otherwise mwhd will load vesa and on modern systems, this will just lead to a black screen, because vesa-xorg can not run on KMS-enabled systems.

So the Idea was to use Opensource drivers always as fallback - in cases they are from AMD/NVIDIA/INTEL. This will not change anything for users of them, all the old scripts are just merged into one "big".

As always this script will not add any file to the system. It just lets linux itself handle the situation. So if your graphicscard is supported by linux, it will work. No mhwd conflicts anymore.

On top of that it also phases out the bumblebee scripts on installation time by uninstalling all file and deactivating the bumblebee service. So right after a system restart you wont have bumblebee (but still prime)

**Remember that this is only for opensource drivers. It will not interact with th nonfree Nvidia/Catalyst in any way.**

On the downside it will use a few more MiB on space on users computer, because all the parts are installed on every system (just like radeon-vulkan on intel only systems). But this is in the "up to 5MiB" range, so no big deal and if the user wants to remove it - thats fine.

About the name "video-linux" - it's because this script is about using the standard linux graphicsstack.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
This needs to be tested @Tids. I've uplaoded a new **mhwd-db** to our [unstable](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20180212/014915.html) branch. It would be best to create a new ISO and test it on some laptops ...

CC @oberon2007

**Comment by Tids** [comment]
@philmmanjaro I'm unable to build an iso. For some unknown reason mhwdfs wont build. not on unstable, not on stable. I dont know whats wrong here

```
buildiso -p kde -b unstable -k linux415 -r /home/share/buildersplace -t /home/share/buildersplace
[...]
 --> Loading Packages: [Packages-Mhwd] ...
==> Prepare [drivers repository] (mhwdfs)
 --> overlayfs mount: [/home/share/buildersplace/kde/x86_64/mhwdfs]
 --> Restoring [/home/share/buildersplace/kde/x86_64/mhwdfs/etc/pacman.conf] ...
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : linux415-bbswitch  linux415-broadcom-wl  linux415-r8168  linux415-rt3562sta  linux415-virtualbox-guest-modules  libva-intel-driver  libva-mesa-driver  libva-vdpau-driver  lib32-libva-vdpau-driver  libxaw  libxpm  libxvmc  mesa-vdpau  lib32-mesa-vdpau  lib32-libxvmc  lib32-primus  catalyst-utils  linux415-catalyst  linux415-nvidia  linux415-nvidia-304xx  linux415-nvidia-340xx  nvidia-304xx-utils  nvidia-340xx-utils  nvidia-utils  lib32-catalyst-utils  lib32-nvidia-304xx-utils  lib32-nvidia-340xx-utils  lib32-nvidia-utils  opencl-mesa  open-vm-tools  pangox-compat  primus  bumblebee  virtualbox-guest-utils  vulkan-radeon  lib32-vulkan-radeon  vulkan-intel  lib32-vulkan-intel  xf86-input-vmmouse  xf86-video-amdgpu  xf86-video-ati  xf86-video-dummy  xf86-video-fbdev  xf86-video-intel  xf86-video-nouveau  xf86-video-openchrome  xf86-video-sisusb  xf86-video-vesa  xf86-video-vmware  xf86-video-voodoo
:: Synchronizing package databases...
 core                     141.5 KiB   804K/s 00:00 [######################] 100%
 extra                   1713.8 KiB  2.77M/s 00:01 [######################] 100%
 community                  4.4 MiB  2.76M/s 00:02 [######################] 100%
 multilib                 174.1 KiB  2.79M/s 00:00 [######################] 100%
error: target not found: linux415-rt3562sta
error: target not found: linux415-rt3562sta
  -> Copying mhwd package cache ...
building file list ... done

sent 16 bytes  received 12 bytes  56.00 bytes/sec
total size is 0  speedup is 0.00
==> ERROR: File '/home/share/buildersplace/kde/x86_64/mhwdfs/opt/pkg/*pkg*z' not found.
==> Creating updated database file '/home/share/buildersplace/kde/x86_64/mhwdfs/opt/pkg/mhwd.db.tar.gz'
==> WARNING: No packages remain, creating empty database.
==> WARNING: No packages remain, creating empty database.
 --> Configuring mhwd db ...
  -> Disabling Catalyst driver
  -> Disabling Nvidia driver
  -> Disabling Nvidia Bumblebee driver
  -> Disabling Nvidia 304xx driver
  -> Disabling Nvidia 340xx driver
  -> Disabling AMD gpu driver
  -> Disabling VirtualBox guest driver
 --> overlayfs umount: [/home/share/buildersplace/kde/x86_64/mhwdfs]
  -> Cleaning [mhwdfs]
==> Done [drivers repository] (mhwdfs)
```

**Comment by oberon2007** [comment]
|error: target not found: linux415-rt3562sta This module doesn't exist
for linux415! ;) |

**Comment by oberon2007** [comment]
This rt3562sta module fails to build for linux415.
You will just have to comment 'KERNEL-rt3562sta' in
'/shared/Packages-Mhwd' (and 'Packages-Live-Xorg' if used).

**Comment by philmmanjaro** [comment]
Yes, that driver doesn't exist for that branch of the kernel series yet. Commenting it out should solve it. Please use `buildiso -p kde -b unstable -k linux415 -r /home/share/buildersplace -t /home/share/buildersplace -c` to continue your build after fixing this.

**Comment by philmmanjaro** [comment]
Test ISOs: [download link](https://cloud.fabi.sh/index.php/s/9fxfFynd49dKHSg)

**Comment by mirh** [comment]
Mhh.. `Video-linux` is kind of an anonymous and indistinct name though to be honest. 
(or maybe, was it just me lost because I didn't see video-ati anymore?)

**Comment by Tids** [comment]
@mirh But its what it is, graphicsdrivers provided by linux. It's the most simple name.

**Pull request merged**
